service: github-handyman

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10
  region: ${file(share/terraform/terraform.json):aws_region}
  memorySize: 128
  environment:
    GH_TOKEN: ${env:GH_TOKEN}
    GH_OWNERS: ${env:GH_OWNERS}

plugins:
  - serverless-plugin-include-dependencies

package:
  exclude:
    - node_modules/**
    - .serverless/**
    - serverless.yml
    - .git/**
    - .gitignore
    - .idea/**
    - '*.iml'
    - test/**
    - package.json
    - .babelrc
    - .eslintignore
    - .eslintrc
    - README.md
    - src/**
    - coverage/**

functions:
  handler:
    handler: build/index.handler
    events:
      - schedule: rate(30 minutes)
    timeout: 240

resources:
  Resources:
    HandlerLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: 30
