service: github-handyman

frameworkVersion: ">=1.1.0 <3.0.0"

provider:
  name: aws
  stage: ${opt:stage, 'production'}
  runtime: nodejs12.x
  region: ${file(share/terraform/terraform.json):aws_region}
  memorySize: 128
  deploymentBucket:
    name: ${file(share/terraform/terraform.json):aws_s3_bucket}
    maxPreviousDeploymentArtifacts: 3
    blockPublicAccess: true
  deploymentPrefix: serverless
  versionFunctions: false
  role: ${file(share/terraform/terraform.json):aws_iam_role_arn}
  logRetentionInDays: 30
  vpc:
    subnetIds: ${file(share/terraform/terraform.json):aws_subnet_ids}
    securityGroupIds: ${file(share/terraform/terraform.json):aws_security_group_ids}
  environment:
    GITHUB_HANDYMAN_GITHUB_TOKEN: ${env:GITHUB_HANDYMAN_GITHUB_TOKEN}
    GITHUB_HANDYMAN_WHITELISTED_ORGS: ${env:GITHUB_HANDYMAN_WHITELISTED_ORGS}
  tracing:
    lambda: true

plugins:
  - serverless-plugin-include-dependencies

package:
  exclude:
    - .github/**
    - node_modules/**
    - .serverless/**
    - serverless.yml
    - .git/**
    - .gitignore
    - .idea/**
    - '*.iml'
    - test/**
    - package.json
    - package-lock.json
    - .babelrc
    - .eslintignore
    - .eslintrc
    - CONTRIBUTING.md
    - README.md
    - LICENSE.md
    - src/**
    - coverage/**
    - share/**

functions:
  handler:
    handler: build/index.handler
    events:
      - schedule: rate(1 hour)
    timeout: 600
