name: Integration

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10.13
      - name: Install NPM dependencies
        run: |
          npm install
          npm prune
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm test
      - name: coveralls
        run: npm run coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - name: semantic-release
        run: npm run semantic-release
